name: sample
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_svg: ^0.22.0
  dio: ^4.0.0
  retrofit: ^3.0.1
  json_serializable: ^6.1.3
  json_annotation: ^4.4.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.7
  logger: ^1.1.0
  intl: ^0.17.0
  profile: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  retrofit_generator: ^3.0.1
  flutter_lints: ^1.0.4
  dartx: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
